// Code generated by purecache. DO NOT EDIT.

package main

import "purecache/cache"

const cacheID_Score = "b567287423c2d6a5f0ff40ed47c5684b2307b7696183ff8f9d277c59e5a8bf2f"

type cacheArgs_Score struct {
	A0 []float64
	A1 Weights
}

// CachedScore is the memoised form of Score.
func CachedScore(xs []float64, w Weights) float64 {
	return cache.Do(cacheID_Score, cacheArgs_Score{xs, w}, func(a cacheArgs_Score) float64 {
		return Score(a.A0, a.A1)
	})
}

const cacheID_SlowFib = "0adee41d6901bdeb9335facd12e723d4125057c931f66158d2c33e4c1ae839a9"

type cacheArgs_SlowFib struct {
	A0 int
}

// CachedSlowFib is the memoised form of SlowFib.
func CachedSlowFib(n int) int {
	return cache.Do(cacheID_SlowFib, cacheArgs_SlowFib{n}, func(a cacheArgs_SlowFib) int {
		return SlowFib(a.A0)
	})
}

const cacheID_TotalCount = "af48459d914b7a32baf9527b5ea8db4f5f6db92a82a289b14a1a998e856b46c3"

type cacheArgs_TotalCount struct {
	A0 map[string]int
}

// CachedTotalCount is the memoised form of TotalCount.
func CachedTotalCount(counts map[string]int) int {
	return cache.Do(cacheID_TotalCount, cacheArgs_TotalCount{counts}, func(a cacheArgs_TotalCount) int {
		return TotalCount(a.A0)
	})
}
